"""sync project model

Revision ID: 4ccd182b0b9b
Revises: df0f3ed177ac
Create Date: 2026-01-21 22:04:42.737019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccd182b0b9b'
down_revision: Union[str, Sequence[str], None] = 'df0f3ed177ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('hero_image_url', sa.String(length=500), nullable=True))
    op.drop_column('projects', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('duration', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('projects', 'hero_image_url')
    # ### end Alembic commands ###
