"""sync services marketing fields

Revision ID: 6b832c6ea2b8
Revises: 6249d337e8ad
Create Date: 2026-01-21 13:14:57.988119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # noqa: F401  (kept in case it's used elsewhere)

# revision identifiers, used by Alembic.
revision: str = "6b832c6ea2b8"
down_revision: Union[str, Sequence[str], None] = "6249d337e8ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE:
    - Subscribers & testimonials tables / indexes are now fully handled
      by revision `2f38897ab12c_add_testimonials_and_subscribers`.
    - This migration is ONLY responsible for adding marketing fields
      to the `services` table.
    """
    # ### commands auto generated by Alembic - adjusted to avoid dropping other tables ###
    op.add_column("services", sa.Column("tagline", sa.String(length=255), nullable=True))
    op.add_column("services", sa.Column("category", sa.String(length=100), nullable=True))
    op.add_column("services", sa.Column("hero_image_url", sa.String(length=500), nullable=True))
    op.add_column("services", sa.Column("icon", sa.String(length=100), nullable=True))
    op.add_column("services", sa.Column("highlight_1", sa.String(length=255), nullable=True))
    op.add_column("services", sa.Column("highlight_2", sa.String(length=255), nullable=True))
    op.add_column("services", sa.Column("highlight_3", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Only reverses the `services` marketing fields added above.
    It does NOT recreate subscribers/testimonials — those belong to
    `2f38897ab12c`.
    """
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column("services", "highlight_3")
    op.drop_column("services", "highlight_2")
    op.drop_column("services", "highlight_1")
    op.drop_column("services", "icon")
    op.drop_column("services", "hero_image_url")
    op.drop_column("services", "category")
    op.drop_column("services", "tagline")
    # ### end Alembic commands ###
