"""sync services marketing fields

Revision ID: 6b832c6ea2b8
Revises: 6249d337e8ad
Create Date: 2026-01-21 13:14:57.988119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b832c6ea2b8'
down_revision: Union[str, Sequence[str], None] = '6249d337e8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_testimonials_display_order'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_is_active'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_is_featured'), table_name='testimonials')
    op.drop_table('testimonials')
    op.add_column('services', sa.Column('tagline', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('services', sa.Column('hero_image_url', sa.String(length=500), nullable=True))
    op.add_column('services', sa.Column('icon', sa.String(length=100), nullable=True))
    op.add_column('services', sa.Column('highlight_1', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('highlight_2', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('highlight_3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'highlight_3')
    op.drop_column('services', 'highlight_2')
    op.drop_column('services', 'highlight_1')
    op.drop_column('services', 'icon')
    op.drop_column('services', 'hero_image_url')
    op.drop_column('services', 'category')
    op.drop_column('services', 'tagline')
    op.create_table('testimonials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quote', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('testimonials_pkey'))
    )
    op.create_index(op.f('ix_testimonials_is_featured'), 'testimonials', ['is_featured'], unique=False)
    op.create_index(op.f('ix_testimonials_is_active'), 'testimonials', ['is_active'], unique=False)
    op.create_index(op.f('ix_testimonials_display_order'), 'testimonials', ['display_order'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('subscribers_pkey'))
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###
