"""upgrade project model

Revision ID: df0f3ed177ac
Revises: 6b832c6ea2b8
Create Date: 2026-01-21 21:58:07.962950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0f3ed177ac'
down_revision: Union[str, Sequence[str], None] = '6b832c6ea2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('duration', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('size', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('technologies', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('projects', 'hero_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('hero_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('projects', 'technologies')
    op.drop_column('projects', 'size')
    op.drop_column('projects', 'duration')
    op.drop_column('projects', 'type')
    op.drop_column('projects', 'thumbnail')
    # ### end Alembic commands ###
