"""phase1_core_models

Revision ID: e5792ceeb4d4
Revises: c296d405ca42
Create Date: 2026-01-12 14:49:50.378940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5792ceeb4d4'
down_revision: Union[str, Sequence[str], None] = 'c296d405ca42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('assigned_to_id', sa.UUID(), nullable=True))
    op.create_index('ix_inquiries_assigned_to_id', 'inquiries', ['assigned_to_id'], unique=False)
    op.create_foreign_key(None, 'inquiries', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_index('ix_inquiries_assigned_to_id', table_name='inquiries')
    op.drop_column('inquiries', 'assigned_to_id')
    # ### end Alembic commands ###
